sportcoders/dynasty-mommy

backend/package.json
backend/src/controller/user.ts
backend/src/middleware/authenticate.ts
backend/src/models/user.ts
backend/src/utils/jwt.ts

this needs to be merged so the dockerfile can be built

utils, model, controller and middleware added for user auth

---

frontend/src/feature/leagues/components/SleeperLeaguesHomePage.tsx

…x, such that if there is no team key in accordian will still be unique

DM-23-Fix-for-key-field-with-multiple-null-unassigned-teams

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/DisplayLeaguesList.tsx
frontend/src/feature/search/components/SleeperSearch.tsx
frontend/src/main.tsx
frontend/src/styles/theme.ts

Implemented baseThemeOptions 
Implemented extensions of the base theme called lightThemeOptions & darkThemeOptions (light & dark mode for future use)
ThemeOptions only include colors for now
Refactored component styling for HomePage and its used features & components to match the theme

DM-22 global styling using theme provider

---

.vscode/settings.json
frontend/src/services/sleeper/apiClient.ts
frontend/src/services/sleeper/avatar.ts
frontend/src/services/sleeper/leagues.ts
frontend/src/services/sleeper/player.ts
frontend/src/services/sleeper/user.ts
frontend/src/utils/errors.ts
frontend/tsconfig.app.json
frontend/tsconfig.json
frontend/vite.config.ts

Implemented custom error classes
Removed error handling in service functions for the errors to bubble up until handled in the top-level
Need to add try/catch in top-level calls and display custom error notifications or else the component will crash instead of rendering the error-free parts

DM-49-Service-Error-handling-for-apiClient

---

frontend/src/feature/search/hooks/useDeleteLeague.ts
frontend/src/feature/search/hooks/useSaveLeague.ts
frontend/src/providers/AppProviders.tsx

DM-96-Sleeper-Search-Show-notification-for-adding-removing-leagues

---

frontend/src/feature/leagues/components/SleeperLeaguesHomePage.tsx
frontend/src/feature/leagues/hooks/useGetPreviousSeasons.ts
frontend/src/services/sleeper/types.ts

transactions now show player names and team names
new useeffects should be migrated to use query in the future
we still need to load transactions by week instead of all at once

DM-95 league transaction details

---

frontend/src/feature/leagues/components/SleeperLeaguesHomePage.tsx
frontend/src/feature/navbar/components/navbar.tsx

DM-91-Reset-search-params-when-navigating-from-navbar

---

frontend/src/feature/leagues/components/SleeperLeaguesHomePage.tsx
frontend/src/feature/leagues/hooks/useSleeperPlayers.ts
frontend/src/services/sleeper/leagues.ts

Please check for any bugs. I removed the use of the hook, getting roster by roster id. Not sure if any existing code has a dependency on it

DM-100-League-Fix-roster-loading-transition

---

frontend/src/feature/leagues/components/SleeperTransactionsTab.tsx
frontend/src/feature/leagues/hooks/useGetPlayersInTransaction.ts

Changes
- moved from useSuspenseQuery to useQuery

DM-147 fixed bug causing whole page to show circular loading

---

backend/src/config/config.ts
backend/src/controller/auth.ts
backend/src/routes/auth.ts

NOTE
- currently using render backend as yahoo requires https connection for their api
- redirect url will have to be updated
Changes
- added route to get token from yahoo
Future work
- will need to update redirect uri when backend is finalized, or put this in env/config
- will need to create routes in backend to query yahoo from backend to return to frontend
- frontend will have to be created

DM-152 added route for yahoo callback

---

frontend/src/feature/navbar/components/Navbar.tsx
frontend/src/feature/search/sleeper/components/SleeperLeaguesList.tsx
frontend/src/feature/search/sleeper/components/SleeperSearch.tsx
frontend/src/routes/index.tsx

Frontend Changes:
- Explicitly ordered the search parameters for consistency throughout the app for sleeper search feature

DM-158-Search-Explicit-Parameter-Ordering-in-Navigation

---

frontend/src/routes/index.tsx

Frontend Changes:
- Added search param validation before component load in index route (search route)

DM-157-Search-Fix-validation-for-search-URL-params

---

frontend/src/feature/search/sleeper/components/SleeperLeaguesList.tsx
frontend/src/routes/index.tsx

Frontend Changes:
- Edited css styling in SleeperLeagueList (scrollbar, overflow, height, & flex-column)

DM-150-when-sleeper-user-is-in-a-bunch-of-leagues-the-list-of-leagues-takes-up-the-whole-page-and-the-user-is-unable-to-see-any-navigation

---

frontend/src/feature/search/espn/EspnCookieInstructions.tsx
frontend/src/feature/search/espn/EspnSearch.tsx
frontend/src/pages/HomePage.tsx

Changes
- added case to home page to render espn page
- added espn home page and instructions for cookies

DM-184 added search page for espn

---

backend/src/controller/yahoo.ts
frontend/src/feature/leagues/yahoo/components/TransactionTab.tsx
frontend/src/services/api/yahoo.ts

Backend Changes
- added query param to ask for certain page
- one page is 25 transactions
Frontend Changes
- use infinite query to fetch
- lazy loading the transactions

DM-185 yahoo transactions find way to stream them in load in when in view

---

frontend/src/feature/search/yahoo/components/YahooLeagueSearch.tsx
frontend/src/services/sleeper/apiClient.ts

Changes
- frontend now utilizes refresh route when access token has expired
- yahoo leagues list bug fixed where leagues would still show after the user logged out

DM-149 implement refresh route

---

frontend/src/feature/auth/hooks/useLoginForm.ts
frontend/src/feature/auth/hooks/useSignUpForm.ts

Changes
- redux username state is now set after user sign up
- after user login, user will be directed to the page they clicked login from

DM-186 navigate to the page the user was on previously after they login

---

backend/src/controller/user.ts
backend/src/models/sleeper_league.ts
backend/src/models/user.ts
backend/src/orm.ts
backend/src/routes/user.ts
backend/src/tests/integration/user.test.ts

Changes
- removed user leagues model and isUserLeagues endpoint
- added cascade to sleeper_leagues

DM-187 added cascade to sleeper leagues, removed user_leagues model

---

backend/src/controller/auth.ts
backend/src/routes/auth.ts
frontend/src/feature/navbar/components/Navbar.tsx
frontend/src/services/api/user.ts

Changes
- added logout path in backend to clear cookies
- when user clicks on logout in navbar their cookies will be clear via request to backend.

DM-191 add logout path

---

.github/workflows/google-cloudrun-docker-deploy.yml
.github/workflows/node-backend.yml
backend/src/config/yahooConfig.ts
backend/src/controller/yahoo.ts
backend/src/middleware/yahooTokenCheck.ts
backend/src/routes/yahoo.ts
backend/src/types/yahoo.ts

Changes
- yahoo config file
- added middleware for getting tokens on yahoo requests
Yahoo Config File
- added config for yahoo env variables
- updated existing env variable names
- added additional env variables
- updated workflow for github actions

DM-201 backend yahoo add middleware to simplify token getting
